version: "3.8"
services:
  web:
    image: ${WEB_IMAGE_NAME}
    container_name: bagel-web
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: ${NGINX_IMAGE_NAME}
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
