version: "3.8"
services:
  web:
    image: ${WEB_IMAGE_NAME}
    container_name: bagel-web
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: always

  app:
    image: ${APP_IMAGE_NAME}
    container_name: bagel-app
    networks:
      - app-network
    ports:
      - "4000:4000"
    environment:
      - BAGEL_APP_PORT=4000
      - BAGEL_GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - BAGEL_FS_USER_COLLECTION=${USER_COLLECTION}
    restart: always
    depends_on:
      - web

  nginx:
    image: ${NGINX_IMAGE_NAME}
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - web
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
